/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GNRSJNIInterface */

#ifndef _Included_GNRSJNIInterface
#define _Included_GNRSJNIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GNRSJNIInterface
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GNRSJNIInterface_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     GNRSJNIInterface
 * Method:    insert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GNRSJNIInterface_insert
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     GNRSJNIInterface
 * Method:    update
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GNRSJNIInterface_update
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     GNRSJNIInterface
 * Method:    lookup
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GNRSJNIInterface_lookup
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
