#!/bin/bash
if [ -n "${gnrsLogfile+1}" ]; then
  echo "Using log file ${gnrsLogfile}"
else
  gnrsLogfile='/var/log/gbench.log'
fi
/usr/bin/java -mx256m -DgnrsLogfile=${gnrsLogfile} -cp /usr/local/bin/gnrs/gnrs.jar edu.rutgers.winlab.mfirst.client.TraceClient $@
