#!/bin/bash
if [ -n "${gnrsLogfile+1}" ]; then
	echo "Using log file ${gnrsLogfile}"
else
	gnrsLogfile='/var/log/gnrsd.log'
fi
/usr/bin/java -ms128m -mx128m -DgnrsLogfile=${gnrsLogfile} -jar /usr/local/bin/gnrs/gnrs.jar $@
